local_costmap:
   global_frame: /odom
   robot_base_frame: /base_link
   update_frequency: 5.0  #changing 1.0 to 10.0
   publish_frequency: 2.0 #changing 1.0 to 10.0
   static_map: false       #changing to false
   rolling_window: true
   width: 3.0
   height: 3.0
   resolution: 0.05
   transform_tolerance: 5.0
   map_type: costmap
